# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.stackedWidget.setMinimumSize(QtCore.QSize(1024, 600))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.homePage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 10, 691, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPushButton.sizePolicy().hasHeightForWidth())
        self.startPushButton.setSizePolicy(sizePolicy)
        self.startPushButton.setStyleSheet("")
        self.startPushButton.setFlat(False)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout.addWidget(self.startPushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopPushButton.sizePolicy().hasHeightForWidth())
        self.stopPushButton.setSizePolicy(sizePolicy)
        self.stopPushButton.setStyleSheet("")
        self.stopPushButton.setFlat(False)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout.addWidget(self.stopPushButton)
        self.restartPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.restartPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartPushButton.sizePolicy().hasHeightForWidth())
        self.restartPushButton.setSizePolicy(sizePolicy)
        self.restartPushButton.setStyleSheet("")
        self.restartPushButton.setObjectName("restartPushButton")
        self.horizontalLayout.addWidget(self.restartPushButton)
        self.label = QtWidgets.QLabel(self.homePage)
        self.label.setGeometry(QtCore.QRect(10, 150, 300, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/NO name NO bg 2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.homePage)
        self.goPage = QtWidgets.QWidget()
        self.goPage.setObjectName("goPage")
        self.addItemPushButton = QtWidgets.QPushButton(self.goPage)
        self.addItemPushButton.setGeometry(QtCore.QRect(0, 504, 260, 70))
        self.addItemPushButton.setObjectName("addItemPushButton")
        self.removeItemPushBUtton = QtWidgets.QPushButton(self.goPage)
        self.removeItemPushBUtton.setGeometry(QtCore.QRect(260, 504, 260, 70))
        self.removeItemPushBUtton.setObjectName("removeItemPushBUtton")
        self.pushButton = QtWidgets.QPushButton(self.goPage)
        self.pushButton.setGeometry(QtCore.QRect(780, 430, 100, 100))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    width: 100px;\n"
"    height: 100px;\n"
"    border-radius: 50px; /* Half of the button\'s width/height */\n"
"    font-size: 18px; /* Text size */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.itemsSelectedScrollArea = QtWidgets.QScrollArea(self.goPage)
        self.itemsSelectedScrollArea.setGeometry(QtCore.QRect(0, 300, 520, 201))
        self.itemsSelectedScrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.itemsSelectedScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.itemsSelectedScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.itemsSelectedScrollArea.setWidgetResizable(True)
        self.itemsSelectedScrollArea.setObjectName("itemsSelectedScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 504, 199))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.itemsSelectedScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.goPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startPushButton.setText(_translate("MainWindow", "START"))
        self.stopPushButton.setText(_translate("MainWindow", "STOP"))
        self.restartPushButton.setText(_translate("MainWindow", "RESTART"))
        self.addItemPushButton.setText(_translate("MainWindow", "ADD"))
        self.removeItemPushBUtton.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton.setText(_translate("MainWindow", "GO"))
